### PR TITLE
added grib idx extract methods and test cases

### PR DESCRIPTION
**Pull request by Anu-Ra-g**
The `extract_datatree_chunk_index` function is essential for mapping the idx and grib metadata to make a mapping from one to the other for a particular model horizon file. Also, the mapping method inside the workflow uses the `extract_datatree_chunk_index`  internally.

### CODE REVIEW

**Comment by martindurant** [comment]
Sorry it has taken me so long to start looking at this.

Can you please provide a description for this PR, what the two main functions here are for, how they are expected to be used?

**Comment by Anu-Ra-g** [comment]
The `extract_datatree_chunk_index` function travel through each of the node in the datatree and extracts the grib metadata and returns it in the form of a `Dataframe.`
```
dt_instance = datatree.open_datatree(...)
extract_datatree_chunk_index(dt_instance, kerchunk_store)
```

**Comment by martindurant** [comment]
Yes, but why, what are you supposed to do with this new code?

> No description provided.

**Comment by Anu-Ra-g** [comment]
The dataframe from this function and the dataframe from the `parse_grib_idx` function are used in the mapping.

**Comment by martindurant** [comment]
Please fill out the description of this PR at the top, saying why this new code should be included.

> This mapping provides a aggregrate view of the dataset.

Please demonstrate how the code is supposed to be used.

**Pull request merged**
