### PR TITLE
combine with low memory

### PR DESCRIPTION
**Pull request by martindurant**
This loads all the filesystems to be combined *twice*. If successful, may provide a flag for high versus low memory operation.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I tried using this PR but it seems to take the same amount of memory and be 20% or so slower

**Comment by martindurant** [comment]
@rsignell-usgs , maybe better now?

**Comment by rsignell-usgs** [comment]
@martindurant , yes, better!   You [reported that combining 13 years took 13GB max of memory](https://github.com/fsspec/kerchunk/issues/209#issuecomment-1353647763) with the version in this PR:  

Here's what I got, combining 13 years:
* using this PR, version `0.0.1+420.gca577c4.dirty':  19GB max, Wall Clock 13min45s
* using the latest version from Main `0.0.9+69.g9f9076c.dirty`:  crashed server w/ 32GB memory

So better memory usage, but still requires more than many JupyterHub users will have.   

And I still can't create a single combined JSON for my dataset on the ESIP Qhub, even with the low-memory PR.   I want to combine the 40 years, but I can't even combine 20 without blowing out the 32GB memory!

**Comment by martindurant** [comment]
Can you do 4x10 years, though, and then combine those?

**Comment by rsignell-usgs** [comment]
@martindurant , no, I can't.  I can create the four decadal JSONs, but I can't combine even 2 of them with 32GB memory:
https://nbviewer.org/gist/cce070d4917aeb8d837c7259e3e6ff1a

**Comment by martindurant** [comment]
@rsignell-usgs , I don't know if you can see my qhub "Untitled.ipynb". We can talk about this sometime.

**Comment by rsignell-usgs** [comment]
With the new parquet lazy loading approach, I can load this dataset comfortably on an 8GB memory JupyterHub.   Hurrah!

Here's the proof:
https://nbviewer.org/gist/rsignell-usgs/77609e86825c9c6163af15f90590b440

**Comment by martindurant** [comment]
Yep, so the combine step was "standard" and needed loads of RAM, and the resulting dict/JSON output was then transformed to parquet. We do not have a way to combine directly with parquet right now, but at least the final output was usable.

**Pull request closed without merging**
