### PR TITLE
Make dict-string codec and apply to HDF5

### PR DESCRIPTION
**Pull request by martindurant**
See #32 

@ajelenak - this doesn't work yet, because the resulting filter object isn't JSON encodable (it contains bytestrings). I assume there's a specific way I'm supposed to handle this.

### CODE REVIEW

**Comment by martindurant** [comment]
@ajelenak , I believe this now ought to work, but I get a hard malloc crash (pointer being freed was not allocated). Can you please help me diagnose?

**Comment by ajelenak** [comment]
My first attempt at helping is to recommend a different approach: read the vlen string array and store it in the ReferenceFileSystem JSON. This could be controlled via an option specifying the max byte size of such arrays. Any string array over this max limit would not be stored and this ties in nicely with the similar discussion in #39.

Even the HDF5 code example for reading vlen strings does not use the internal HDF5 struct that is in those "S16" bytes.

**Comment by martindurant** [comment]
Hm, I'm not sure how many data arrays we can possibly inline into the JSON. In the case in hand, the first array would be 63kB with vlen bytes (+expansion with base64), so very doable, but there are many of these in the dataset. The current highest threshold for inlining data I've used is 500bytes.

Even so, I'd really like to know why the code as given in this PR crashes.

**Comment by ajelenak** [comment]
> Hm, I'm not sure how many data arrays we can possibly inline into the JSON. In the case in hand, the first array would be 63kB with vlen bytes (+expansion with base64), so very doable, but there are many of these in the dataset. The current highest threshold for inlining data I've used is 500bytes.

It's the last resort solution, the real goal is to avoid having HDF5 vlen datatypes in files that are to be accessed via ReferenceFileSystem. In this case, I think the source of those vlen HDF5 string datasets is the netCDF library which uses the vlen UTF-8 encoded HDF5 string datatype by default.

> Even so, I'd really like to know why the code as given in this PR crashes.

Can you post the traceback, if there was any? One problem could be the double-use of the `h5f` file-like object in `_make_string_dict()`. `h5f` is already in use by the HDF5 library's virtual file driver (VFD) machinery because h5py opens the HDF5 file with it. An option could be to use the [`H5Dread_chunk()`](http://v1-12-1.hdf5.info/group___h5_d.html#title27) function but those string netCDF variables would need to be chunked (one chunk is enough). @tedhabermann can you create a new file with chunk string variables?

**Comment by martindurant** [comment]
> It's the last resort solution, the real goal is to avoid having HDF5 vlen datatypes in files that are to be accessed via ReferenceFileSystem.

We can't have that goal, as the whole purpose of this effort is to allow access to as wide a range of HDF files as possible, whose provenance we do not control.

> Can you post the traceback, if there was any?

No traceback
```
python(84985,0x109fbadc0) malloc: *** error for object 0x7fdd7b0c2410: pointer being freed was not allocated
python(84985,0x109fbadc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

`_make_string_dict` only takes the h5 object and the open file-like (python `io.BufferedReader` for a local file)

**Comment by martindurant** [comment]
@ajelenak : switching to VLenBytes still results in a segfault or malloc crash, apparently during garbage collection. I put in some manual cleanup to the end of `_translator`, but it makes no difference.

**Comment by ajelenak** [comment]
Do you get segfault when these four lines https://github.com/intake/fsspec-reference-maker/blob/642570d7522647a3583b0eae113377020a107731/fsspec_reference_maker/hdf.py#L315-L318 are commented out?

**Comment by martindurant** [comment]
> Do you get segfault when these four lines

Yes - those lines are not even being called as of the latest commit.

**Comment by tedhabermann** [comment]
@ajelenak - a chunk vlen str? You mean write this dataset as chunked? In this case the dataset is written by the xArray to_netcdf function... Not sure how to control that... I'm actually not sure what chunking means in a variable-length string array...

**Comment by ajelenak** [comment]
@tedhabermann That was last week's idea, not needed any more.

**Comment by ajelenak** [comment]
@martindurant What OS did you run this code on? If not Linux, can you try it there?

**Comment by martindurant** [comment]
It was mac - sure, I can try linux

On July 15, 2021 9:44:57 PM EDT, Aleksandar Jelenak ***@***.***> wrote:
***@***.*** What OS did you run this code on? If not Linux, can you
>try it there?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/fsspec-reference-maker/pull/40#issuecomment-881115990

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment]
Dies:

```
In [9]: out = sin.translate()
2021-07-16 17:46:44,316 - h5-to-zarr - DEBUG - translate -- Translation begins
2021-07-16 17:46:44,327 - h5-to-zarr - DEBUG - _translator -- HDF5 group: /AMC2
2021-07-16 17:46:44,331 - h5-to-zarr - DEBUG - _translator -- HDF5 dataset: /AMC2/Datetime
2021-07-16 17:46:44,332 - h5-to-zarr - DEBUG - _translator -- Created Zarr array: <zarr.core.Array '/AMC2/Datetime' (7025,) int64>
2021-07-16 17:46:44,334 - h5-to-zarr - DEBUG - _translator -- _ARRAY_DIMENSIONS = ['AMC2/Datetime']
2021-07-16 17:46:44,371 - h5-to-zarr - DEBUG - _translator -- HDF5 dataset: /AMC2/Solution
2021-07-16 17:46:44,382 - h5-to-zarr - DEBUG - _translator -- Created Zarr array: <zarr.core.Array '/AMC2/Solution' (7025,) object>
2021-07-16 17:46:44,480 - h5-to-zarr - DEBUG - _translator -- _ARRAY_DIMENSIONS = ['AMC2/Datetime']
Segmentation fault
```

**Comment by martindurant** [comment]
@ajelenak ^ that was my linux (docker) run

**Comment by martindurant** [comment]
Running with the original string dictionary maker, I got extra information, hah
```
In [4]: out = sin.translate()
corrupted double-linked list
Aborted
```

**Comment by martindurant** [comment]
Superseded by #175

**Pull request closed without merging**
