### PR TITLE
Ensure `inline_array` keeps attributes

### PR DESCRIPTION
**Pull request by jrbourbeau**
Currently `inline_array` won't keep attrs around for arrays that it inlines. This PR makes sure attrs are preserved. 

cc @martindurant

### CODE REVIEW

**Comment by martindurant** [comment]
We are hitting a hard crash here (on shutdown of the pytest session), which I can only imagine is coming from HDF5 or maybe grib. This will take some debugging...

**Comment by jrbourbeau** [comment]
Just checking, my guess is this failure is happening on `main` too. I don't see how that could be related to the changes here (though maybe I'm missing something)

**Comment by martindurant** [comment]
> this failure is happening on main too

Not locally :|

**Comment by jrbourbeau** [comment]
I just updated the test added here to use a more simple `attrs`. This seemed to help locally, let's see if it helps in CI. I don't know why the previous `attrs` were problematic, but the simplified `attrs` should still be sufficient

**Comment by martindurant** [comment]
Since it's OK for py38 but crashed on py310, suggests a version problem. I note h5py 3.9.0 just came out.

**Comment by martindurant** [comment]
Confirmed: pinning h5py makes tests pass https://github.com/fsspec/kerchunk/actions/runs/5978456412/job/16220596021?pr=349

**Comment by martindurant** [comment]
^ cc @ajelenak

**Comment by martindurant** [comment]
Pushing the temp fix here, and we can deal with whatever is the underlying problem separately.

**Comment by jrbourbeau** [comment]
Thanks @martindurant

**Pull request merged**
